services:
  api_server:
    container_name: "api_server"
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      DB_URL: ${DB_URL}
    ports:
      - 8000:8000
    restart: always
